<?php

return [
    'definitions' => [
        'super-admin'      => ['label' => 'Super Administrator',          'is_system' => true, 'portal' => 'superadmin'],
        'manager'          => ['label' => 'Manager',                      'is_system' => true, 'portal' => 'bu'],
        'finance'          => ['label' => 'Finance / Admin Keuangan',     'is_system' => true, 'portal' => 'finance-hr'],
        'wash-cashier'     => ['label' => 'Kasir POS Wash',               'is_system' => true, 'portal' => 'bu'],
        'atk-cashier'      => ['label' => 'Kasir POS ATK',                'is_system' => true, 'portal' => 'bu'],
        'wash-operator'    => ['label' => 'Operator Wash / Tukang Cuci',  'is_system' => true, 'portal' => 'bu'],
        'noc-operator'     => ['label' => 'NOC / Network Monitoring',     'is_system' => true, 'portal' => 'isp'],
        'field-leader'     => ['label' => 'Leader Jaringan',              'is_system' => true, 'portal' => 'isp'],
        'field-technician' => ['label' => 'Teknisi Lapangan',             'is_system' => true, 'portal' => 'isp'],
        'partner'          => ['label' => 'Mitra / Reseller',             'is_system' => true, 'portal' => 'partner'],
        'customer'         => ['label' => 'Pelanggan',                    'is_system' => true, 'portal' => 'customer'],
    ],

    'migration_map' => [
        'super-admin'               => ['new_role' => 'super-admin',      'job_title' => 'Administrator'],
        'admin'                     => ['new_role' => 'super-admin',      'job_title' => 'Administrator'],
        'executive'                 => ['new_role' => 'manager',          'job_title' => 'Executive'],
        'direktur'                  => ['new_role' => 'manager',          'job_title' => 'Direktur'],
        'bu-manager'                => ['new_role' => 'manager',          'job_title' => 'BU Manager'],
        'area-coordinator'          => ['new_role' => 'field-leader',     'job_title' => 'Koordinator Wilayah'],
        'coordinator'               => ['new_role' => 'field-leader',     'job_title' => 'Koordinator Wilayah'],
        'leader'                    => ['new_role' => 'field-leader',     'job_title' => 'Team Leader'],
        'hrd-manager'               => ['new_role' => 'finance',          'job_title' => 'HRD Manager'],
        'business-support'          => ['new_role' => 'finance',          'job_title' => 'Business Support'],
        'finance'                   => ['new_role' => 'finance',          'job_title' => 'Finance Staff'],
        'customer-care'             => ['new_role' => 'finance',          'job_title' => 'Customer Care'],
        'customer-service'          => ['new_role' => 'finance',          'job_title' => 'Customer Care'],
        'noc-operator'              => ['new_role' => 'noc-operator',     'job_title' => 'NOC Operator'],
        'noc'                       => ['new_role' => 'noc-operator',     'job_title' => 'NOC Operator'],
        'network-operations-center' => ['new_role' => 'noc-operator',     'job_title' => 'NOC Operator'],
        'field-ops'                 => ['new_role' => 'field-technician', 'job_title' => 'Teknisi Lapangan'],
        'technician'                => ['new_role' => 'field-technician', 'job_title' => 'Teknisi Lapangan'],
        'bu-cashier'                => ['new_role' => 'wash-cashier',     'job_title' => 'Kasir'],
        'kasir-wash'                => ['new_role' => 'wash-cashier',     'job_title' => 'Kasir Cuci'],
        'kasir-atk'                 => ['new_role' => 'atk-cashier',      'job_title' => 'Kasir ATK'],
        'bu-staff'                  => ['new_role' => 'wash-operator',    'job_title' => 'Operator Cuci'],
        'karyawan-wash'             => ['new_role' => 'wash-operator',    'job_title' => 'Operator Cuci'],
        'staff-gudang'              => ['new_role' => 'wash-operator',    'job_title' => 'Staff Gudang'],
        'partner'                   => ['new_role' => 'partner',          'job_title' => 'Mitra'],
        'reseller'                  => ['new_role' => 'partner',          'job_title' => 'Mitra Reseller'],
        'customer'                  => ['new_role' => 'customer',         'job_title' => null],
    ],

    'super_admin_role_names' => ['super-admin'],
    'hidden_in_user_management' => ['customer'],
];
