name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Latest Code
        run: |
          cd /var/www/mstore
          git fetch --all
          git reset --hard origin/main
          chmod +x deploy.sh
          ./deploy.sh
